name: Python Soil Predictor CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-soil-predictor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            libmtdev1 \
            libsdl2-2.0-0 \
            libsdl2-image-2.0-0 \
            libsdl2-mixer-2.0-0 \
            libsdl2-ttf-2.0-0


    - name: Run soil predictor
      run: python soil_predictor_app.py
