name: Python Soil Predictor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-soil-predictor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # or whichever version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install pandas numpy scikit-learn  # install basic deps

    - name: Run Soil Predictor
      run: |
        soil_predictor_app.py  # replace with your Python filename
