name: Python Soil Predictor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-soil-predictor:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the soil predictor headless
    - name: Run soil predictor
      run: python soil_predictor_app.py
      env:
        KIVY_WINDOW: mock
